### ISSUE TITLE
Build failures on Latest snips-platform-swift with XCode 9.4.1

### ISSUE THREAD

**Issue by scitesy** [snipsco/snips-platform-swift#12]
Build Failures:
1) snips-platform-swift/SnipsPlatform/Ontology.swift:312:61: '?' must be followed by a call, member lookup, or subscript
2)snips-platform-swift/SnipsPlatform/Ontology.swift:312:30: Cannot invoke initializer for type 'CActionSessionInit' with an argument list of type '(text: UnsafeMutablePointer<Int8>?, intent_filter: UnsafePointer<CStringArray>?, can_be_enqueued: Int, send_intent_not_recognized: Int)'
3)snips-platform-swift/SnipsPlatform/Ontology.swift:393:73: '?' must be followed by a call, member lookup, or subscript
4)snips-platform-swift/SnipsPlatform/Ontology.swift:390:24: Cannot invoke initializer for type 'CContinueSessionMessage' with an argument list of type '(session_id: UnsafeMutablePointer<Int8>!, text: UnsafeMutablePointer<Int8>!, intent_filter: UnsafeMutablePointer<CStringArray>?, custom_data: UnsafeMutablePointer<Int8>?, send_intent_not_recognized: Int)'

**Comment by klefevre** [comment]
Hey @scitesy thanks for the report. This will be fixed in the next release !
