### ISSUE TITLE
snips.start() not working in v0.57.0

### ISSUE THREAD

**Issue by SebanSunny** [snipsco/snips-platform-swift#8]
If i try the Swift Demo example, the line 137 gives the following error:
`
Can't add detector
 -> caused by: Model default_hotword not registered
`

**Comment by klefevre** [comment]
Hello @SebanSunny 
Thank you for the report, it's indeed a bug. We'll release a fix today or tomorrow !
You might need to revert the latest version to have a project that work (0.56.4).
Thanks again!

**Comment by klefevre** [comment]
The 0.57.1 was released yesterday and should fix your problem. Let me know if you still have problems !
Cheers
